# roles/zabbix-server/tasks/config.yml
---

- name: Configure Zabbix
  template:
    src: zabbix_server.conf.j2
    dest: "{{ zabbix_server_config_server }}"
  notify: restart zabbixserver
  tags: zabbixserver

- name: Ensure service is started
  service:
    name: "{{ zabbix_server_service }}"
    state: started
    enabled: yes
  tags: zabbixserver
  #in vars: zabbixserver_service = zabbix-server