# roles/ROLENAME/tasks/main.yml
---

- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: zabbixserver

- include_tasks: install.yml
- include_tasks: config.yml
- include_tasks: findUnarchive.yml
- include_tasks: SELinux.yml